ocsigen/ocsigenserver

- Makefile.options
- configure
- src/baselib/Makefile
- src/extensions/ocsipersist-dbm/Makefile
Now that lwt.extra has been deprecated [0], the configure and Makefile
scripts should refer directly to lwt.preemptive.
This fix has been tested with `with-preempt` and `without-preempt` options.
[0] https://github.com/ocsigen/lwt/commit/91d549b54397a33ed80de962771d07180c4b8d4e
> fix configure and Makefiles following lwt.extra deprecation

- src/server/ocsigen_generate.ml
ocsigenserver's url parser expects a scheme to be present. This commit
defaults to http if it's absent.
> Workaround for missing scheme in uri

- src/http/ocsigen_senders.ml
Gives a 10% speed boost when serving small files for nearly no effort.
> Ocsigen_senders (File_content): buffer size need not be larger than file

- opam
- src/http/ocsigen_http_com.ml
Lwt_chan (deprecated) is now built atop Lwt_io and allocates a buffer on every
write. Refer to #49.
This makes ocsigenserver over 2X faster at serving large files, and also gives
a measurable improvement (~20%) for smaller ones (in the 10 KB range).
> Ocsigen_http_com: avoid O(response) allocation by using Lwt_io, 2X speedup

- src/server/ocsigen_server.ml
Useful for distinguishing between the various SSL errors: unknown ca, no
shared cipher, unsupported protocol, etc.
If you have access to the client side then you can debug this with 'curl -v' or 'openssl s_client', however that is not always the case and server-side debugging is needed in some situations.
> Log more details about SSL accept error

- src/server/ocsigen_parseconfig.ml
- src/server/ocsigen_parseconfig.mli
- src/server/ocsigen_server.ml
This patch exports some OpenSSL configuration parameters through the configuration file. It covers the parameters discussed in #19.
The syntax is as follows:
```xml
<ssl>
<ciphers>HIGH:!SSLv2:!aNULL:!3DES</ciphers>
<dhfile>/etc/ssl/dh2048.pem</dhfile>
<curve>prime256v1</curve>
</ssl>
```
You can use whatever values OpenSSL considers meaningful.
> Export OpenSSL options through configuration file

- Makefile
- src/Makefile
- src/baselib/Makefile
This addresses issue  #101 
For each impacted Makefile, references to `$(OCSIGENGROUP)` have been replaced with `“$(OCSIGENGROUP)”`.
> Fix for OCSIGENGROUP groups with spaces in the name

- Makefile.options
- opam
- src/baselib/Makefile
- src/baselib/ocsigen_lib_base.ml
- src/baselib/ocsigen_messages.ml
- src/extensions/Makefile
- src/http/Makefile
- src/server/Makefile
This eliminates the use of Camlp4 for the standard library. Still needed for Ocsipersist, but this will be separated-out.
We use Camlp4 so little that I didn't even deem it necessary to use PPX instead.
> Do not use Camlp4 for baselib

- src/baselib/.depend
- src/baselib/Makefile
- src/baselib/ocsigen_stream.ml
- src/extensions/.depend
- src/extensions/deflatemod.ml
- src/extensions/ocsipersist-dbm/.depend
- src/extensions/ocsipersist-pgsql/.depend
- src/extensions/ocsipersist-sqlite/.depend
- src/http/.depend
- src/http/ocsigen_http_com.ml
- src/http/ocsigen_senders.ml
- src/server/.depend
- src/server/ocsigen_server.ml
Use immutable strings as much as possible. Some copying needed.
See discussion in #135.
> Compile with -safe-string (OCaml 4.06)

- README.md
- opam
- src/extensions/ocsipersist-pgsql/Makefile
- src/extensions/ocsipersist-pgsql/ocsipersist.ml
camlp4 is a deprecated tool and should be avoided. This PR remove any remaining uses of camlp4 in ocsigenserver.
> Remove any uses of camlp4

- configure
Replace '=' with ' ' in the configure usage documentation for options
that take arguments, since the configure script is not designed to parse
the '=' characters.
> Clarify configure usage documentation.

- src/baselib/ocsigen_commandline.ml
Handle the Arg.Bad exception and print command line usage to stderr.
Normalize the Arg.Help handler to omit an extra newline when printing
command line usage.
> Gracefully respond to invalid command line options.

- src/baselib/commandline/ocsigen_getcommandline.mli
- src/baselib/nocommandline/ocsigen_getcommandline.mli
This fixes compilation with OCaml 4.07 .
> Add Ocsigen_getcommandline mli's to produce compatible cmi's

- .travis.yml
Also @balat, please add the `GHP_TOKEN` on *travis-ci.org* instead of .com: https://travis-ci.org/ocsigen/ocsigenserver/settings
> Fix GitHub access token name in Travis.

- src/files/META.in
This appears to be a minor issue that triggers a compilation error when using Dune on projects which depend on ocsigenserver.
> fix lwt.react in META.in file

- Makefile.options
- configure
- opam
- src/server/ocsigen_server.ml
Amend the build process and add SIGINT handling (`gmon.out` is only written if the process exits normally).
> Add profiling flag to the config script and make it the default behaviour

- src/baselib/ocsigen_lib.ml
- src/baselib/ocsigen_lib.mli
I don't know if there is an equivalent. I use it in OAuth2/OpenID Connect implementation in Ocsigen-start.
> Add prefix_and_path_of_t

- CHANGES
- configure
- src/baselib/ocsigen_lib_base.ml
- src/baselib/ocsigen_messages.ml
- src/baselib/ocsigen_stream.mli
- src/extensions/cgimod.ml
- src/extensions/deflatemod.ml
- src/extensions/ocsigen_comet.ml
- src/extensions/ocsipersist-dbm/ocsipersist.ml
- src/extensions/staticmod.ml
- src/http/http_headers.mli
- src/http/multipart.ml
- src/http/ocsigen_headers.ml
- src/http/ocsigen_headers.mli
- src/http/ocsigen_http_com.ml
- src/http/ocsigen_http_frame.ml
- src/http/ocsigen_senders.ml
- src/server/ocsigen_extensions.ml
- src/server/ocsigen_extensions.mli
- src/server/ocsigen_http_client.ml
- src/server/ocsigen_http_client.mli
- src/server/ocsigen_parseconfig.mli
- src/server/ocsigen_request_info.ml
- src/server/ocsigen_socket.mli
Typos found with https://github.com/codespell-project/codespell
> Fixing typos

- src/baselib/ocsigen_commandline.ml
- src/baselib/ocsigen_config.ml.in
- src/baselib/ocsigen_config.mli
- src/files/ocsigenserver.1
Ocsigen_config: be a bit less verbose on -v
reverts 20f7f1c66d66a63d077febebc7fe8b169d2af275
> command-line parameters reflecting the verbosity levels of Lwt_log

- opam
- src/baselib/ocsigen_config.ml.in
- src/baselib/ocsigen_messages.ml
- src/extensions/ocsipersist-dbm/ocsipersist.ml
- src/extensions/ocsipersist-pgsql/ocsipersist.ml
- src/extensions/ocsipersist-sqlite/ocsipersist.ml
The right way to control the verbosity with regards to logging is to
change the log level.
> always log to console (stderr) not only if -v is given

- src/baselib/ocsigen_commandline.ml
- src/baselib/ocsigen_config.ml.in
- src/baselib/ocsigen_messages.ml
- all sections (including "access") are now prefixed by "ocsigen:"
- default logging level is only applied to "ocsigen:*" instead of "*"
- always log access.log (wasn't previously the case)
- only level warning/error/fatal points to stderr, otherwise to stdout
> fix logging issues

- src/server/ocsigen_server.ml
We are dynamically loading code that may call `Lwt_main.run`, but this function cannot be nested in Lwt 5.
> No longer run initialization code within Lwt_main.run

- opam
- src/extensions/ocsipersist-dbm/ocsipersist.ml
- src/extensions/ocsipersist-pgsql/ocsipersist.ml
- src/extensions/ocsipersist-sqlite/ocsipersist.ml
- src/extensions/ocsipersist.mli
New functorial interface allows for different column types in
Sqlite/PostgreSQL instead of storing everything as text/blobs/strings.
This way keys and values can be stored and retrieved without
necessarily marshalling/unmarshalling them. This allows for better
readability of the data in the DB for instance via the psql interactive
terminal, and for higher-performance organisation of the data.
> functorial interface for Ocsipersist

- src/server/ocsigen_request.ml
@vouillon You changed this some time ago. Are you ok with this version?
It fixes actions. update ~post_params:None was not removing post params.
> Fix cohttp version of Ocsigen_request.update

- opam
- src/server/ocsigen_server.ml
Currently the following piece of server-side code will make the server crash:
let () = Lwt.async @@ fun () -> failwith __LOC__
> set Lwt.async_exception_hook earlier to catch early exceptions

- ocsigenserver.opam
- src/Makefile
- src/server/ocsigen_multipart.ml
This should render https://github.com/ocsigen/ocsigenserver/pull/206 obsolete.
> remove obsolete package dependencies; remove hack from src/Makefile

- Makefile.options
- configure
- ocsigenserver.opam
- src/baselib/dune
- src/baselib/ocsigen_lib.ml
- src/baselib/ocsigen_lib.mli
- src/baselib/ocsigen_loader.ml
- src/baselib/ocsigen_stream.ml
- src/extensions/outputfilter.ml
- src/extensions/outputfilter.mli
- src/extensions/redirectmod.ml
- src/extensions/revproxy.ml
- src/extensions/rewritemod.ml
- src/extensions/staticmod.ml
- src/http/ocsigen_charset_mime.ml
- src/http/ocsigen_charset_mime.mli
- src/server/ocsigen_cohttp.ml
- src/server/ocsigen_extensions.ml
- src/server/ocsigen_extensions.mli
- src/server/ocsigen_multipart.ml
- src/server/ocsigen_parseconfig.ml
This pull request removes the need for obsolete libraries:
- cohttp 4.x: the fix is simple and already reported in #228 
- pcre: I chose to fix this one by using re instead (see https://github.com/mmottl/pcre-ocaml/issues/25)
> Fix obsolete libraries

- src/http/dune
- src/server/dune
The 'http' library conflicts with the 'http' library distributed by cohttp: https://ocaml.org/p/http/latest
This is an internal change only, as the library is unwrapped and no module is renamed.
> Rename the 'http' library to 'ocsigen_http'

- src/server/ocsigen_cohttp.ml
This code was possibly intended to detect connections that are never closed. But it is currently unused and is tricky to reason about in the context of the migration to direct-style.
> server: Simplify 'get_number_of_connected'

- src/baselib/ocsigen_cache.ml
- src/baselib/ocsigen_lib.ml
- src/baselib/ocsigen_stream.ml
- src/baselib/tests/test_wrapping.ml
- src/extensions/accesscontrol.ml
- src/extensions/authbasic.ml
- src/extensions/deflatemod.ml
- src/extensions/extendconfiguration.ml
- src/extensions/staticmod.ml
- src/server/ocsigen_cohttp.ml
- src/server/ocsigen_extensions.ml
- src/server/ocsigen_local_files.ml
- src/server/ocsigen_multipart.ml
- src/server/ocsigen_server.ml
This helps find ignored Lwt threads, which are a challenge to translate into direct-style concurrency. Ignoring a Lwt thread makes it implicitly fork in the background, which requires an explicit call with other concurrency libraries.
This makes finding these implicit forks a lot easier at the expense of added type annotations. 
Occurrences of ignored values were found using [this tool](https://github.com/Julow/lwt-to-direct-style/pull/9). Running this again in the future is not needed and type annotation can be removed later if needed.
Thanks @raphael-proust for suggesting the idea.
> Add type annotation to ignored values

- test/server-test-helpers.sh
The `cut` command stripping away the date of log messages broke at the beginning of the month due to using `' '` as a separator. Instead, we can count on the date format to always be 16 characters long and make the `cut` command more robust.
> test: Fix unstable tests due to date in logs

- src/server/ocsigen_config.ml
- src/server/ocsigen_config.mli
- src/server/ocsigen_parseconfig.ml
- src/server/ocsigen_server.ml
- src/server/ocsigen_server.mli
`Lwt_preemptive` is not used in any Ocsigen projects and will make less sense with other concurrency libraries.
This removes the call to `Lwt_preemptive.init` and the `maxdetachedcomputationsqueued` config option.
> Remove usage of 'Lwt_preemptive'

- src/server/ocsigen_cohttp.ml
- src/server/ocsigen_request.ml
- src/server/ocsigen_request.mli
- src/server/ocsigen_server.ml
This makes `Ocsigen_request.t` lighter and remove a source of exceptions.
Value of type `Unix.sockaddr` were constructed for purposes other than performing network calls and can easily be replaced by a string.
Accesscontrol is the only user of parsed IP addresses, which doesn't justifies the weight added to the request record.
This removes a source of exception for every requests.
> Remove usage of Unix.sockaddr type

- src/server/ocsigen_cohttp.ml
- src/server/ocsigen_request.ml
- src/server/ocsigen_request.mli
This reverts commit 7b1965c30eec4a5c969f35fadb15acceac374825.
Partially revert https://github.com/ocsigen/ocsigenserver/pull/270 as it's unclear whether we can get rid of the `Ipaddr_unix.to_inet_addr` check (that calls `Unix.inet_addr_of_string`).
> Revert "Remove usage of Unix.sockaddr type"
